INSERT INTO `delivery_note_config` VALUES (84, 'LOGISTICS_OPERATOR_X', 10);
INSERT INTO `delivery_note_config` VALUES (85, 'LOGISTICS_OPERATOR_Y', 275);
INSERT INTO `delivery_note_config` VALUES (86, 'LOGISTICS_OPERATOR_PRINT', 1);