insert into `institute`.`role` values (22, 'LOGISTIC_OPERATOR_ASSIGNMENT', 'Asignacion de Operador Logistico');
insert into `institute`.`role` values (23, 'SEARCH_INPUTS', 'Busqueda de Ingresos');
insert into `institute`.`role` values (24, 'SEARCH_OUTPUTS', 'Busqueda de Ingresos');
insert into `institute`.`role` values (25, 'SEARCH_PROVISIONING_REQUEST', 'Busqueda de Pedidos');
insert into `institute`.`role` values (26, 'SEARCH_SUPPLYING', 'Busqueda de Dispensas');
insert into `institute`.`role` values (27, 'SEARCH_DELIVERY_NOTE', 'Busqueda de Remitos');
insert into `institute`.`role` values (28, 'SEARCH_AUDIT', 'Auditoria');
insert into `institute`.`role` values (29, 'SEARCH_STOCK', 'Busqueda de Stock');
insert into `institute`.`role` values (30, 'SEARCH_SERIALIZED_PRODUCT', 'Traza por Serie');
insert into `institute`.`role` values (31, 'SEARCH_BATCH_EXPIRATEDATE_PRODUCT', 'Traza por Lote');
insert into `institute`.`role` values (32, 'AFFILIATE_ADMINISTRATION', 'Administracion de Afiliados');
insert into `institute`.`role` values (33, 'AGENT_ADMINISTRATION', 'Administracion de Agentes');
insert into `institute`.`role` values (34, 'CLIENT_ADMINISTRATION', 'Administracion de Clientes');
insert into `institute`.`role` values (35, 'CONCEPT_ADMINISTRATION', 'Administracion de Conceptos');
insert into `institute`.`role` values (36, 'AGREEMENT_ADMINISTRATION', 'Administracion de Convenios');
insert into `institute`.`role` values (37, 'EVENT_ADMINISTRATION', 'Administracion de Eventos');
insert into `institute`.`role` values (38, 'DELIVERY_LOCATION_ADMINISTRATION', 'Administracion de Lugares de Entrega');
insert into `institute`.`role` values (39, 'LOGISTIC_OPERATOR_ADMINISTRATION', 'Administracion de Operador Logistico');
insert into `institute`.`role` values (40, 'PRODUCT_ADMINISTRATION', 'Administracion de Productos');
insert into `institute`.`role` values (41, 'PROVIDER_ADMINISTRATION', 'Administracion de Proveedores');
insert into `institute`.`role` values (42, 'DELIVERY_NOTE_ENUMERATOR_ADMINISTRATION', 'Administracion de Puntos de Venta');
insert into `institute`.`role` values (43, 'PROVIDER_SERIALIZED_FORMAT_ADMINISTRATION', 'Administracion de Formatos de Serializacion');
insert into `institute`.`role` values (44, 'PROFILE_ADMINISTRATION', 'Administracion de Perfiles');
insert into `institute`.`role` values (45, 'PROPERTY_ADMINISTRATION', 'Administracion de Propiedades');